#!/usr/bin/env perl

use v5.14;

use warnings;
use strict;

use File::Spec;
use Getopt::Long;

use Fcntl 'O_RDWR', 'O_CREAT';
use Tie::File;
use Env;

my ( $filename, $sitename, $verbose ) = ( "properties.ini", "example", 0 );

GetOptions(
    "sitename=s" => \$sitename,
    "file=s"     => \$filename,
    "verbose"    => \$verbose
);

my $properties = tunnel( ".caravan", "sites", $sitename, $filename );

# Functions
# ========================================================== ->
sub base {
    return ( scalar(@_) ) ? File::Spec->catfile( $HOME, @_ ) : $HOME;
}

sub touch {
    my @array = ();

    my $touch = tie @array, 'Tie::File', $_[0], mode => O_RDWR | O_CREAT;
    untie $touch;

    return $_[0];
}

sub tunnel {
    my ( $file, @path ) = ( pop @_, @_ );

    my @current;

    if (@path) {
        foreach my $dir (@path) {
            push @current, $dir;

            if ( !-d base(@current) ) {
                mkdir base(@current);
            }
        }
    }

    push @current, $file;

    my $fullpath = base(@current);

    touch($fullpath) unless ( -e $fullpath );

    return $fullpath;
}

sub caravan {

    my @array =
      ( "#!/usr/bin/env perl", "", "use warnings", "use strict", "use CGI", );

    my $touch = tie @array, 'Tie::File', $_[0], mode => O_RDWR | O_CREAT;
    untie $touch;
}

